name: Auto Merge
on:
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - main
jobs:
  automerge:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request_target' && github.event.pull_request.merged == false && github.event.author.id == 'pfreixes')
    steps:
      - name: Env
        run: env
      - name: Automatic merge
        run: |
          echo ${{ github.event.actor.id }}
          DATA=`curl -XPOST -o - -f \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{repository(owner: "pfreixes", name:"test"){pullRequest(number: ${{ github.event.pull_request.number }}){id}}}' \
            https://api.github.com/graphql`
          echo $DATA
          PR_ID=`echo $DATA | jq -r .data.repository.pullRequest.id`
          echo $PR_id
          curl -XPOST -f \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"query" : "mutation($id:String!){enablePullRequestAutoMerge(input: {pullRequestId:$id}){ clientMutationId }}", "variables" : {"id" : "$PR_ID"}}' \
            https://api.github.com/graphql
      - name: Automatic Approval
        run: |
          curl -XPOST -f \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event":"APPROVE", "body":"Approved automatically."}' \
            https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.number || github.event.issue.number}}/reviews


