name: Auto Merge
on:
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - main
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: env
      - name: Automatic merge
        run: |
          curl -XPOST -f \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"query" : "mutation($id:String!){enablePullRequestAutoMerge(input: {pullRequestId:$id}){ clientMutationId }}", "variables" : {"id" : "${{ github.event.ref }}"}}' \
            https://api.github.com/graphql
      - name: Automatic Approval
        run: |
          curl -XPOST -f \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event":"APPROVE", "body":"Approved automatically."}' \
            https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.number || github.event.issue.number}}/reviews


